import getCurrentUser from "@/app/actions/getCurrentUser"
import NewPostBody from "./page"
import ToasterProvider from "@/app/components/providers/ToasterProvider"
import { redirect } from 'next/navigation';
import AdminNavbar from "@/app/components/navbar/AdminNavbar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function Admin(){

  const currentUser = await getCurrentUser()

  if(!currentUser){
    redirect('/');
  }


  return (
    <div>
        <ToasterProvider />
        <AdminNavbar/>
        <NewPostBody/>
    </div>
    
  )
}





